export const STATUS = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PENDING: "PENDING",
};

export const TRANSACTION_TYPE = {
  WITHDRAWAL: "WITHDRAWAL",
  DEPOSIT: "DEPOSIT",
  PROFIT: "PROFIT",
  REFERRAL_CREDIT: "REFERRAL_CREDIT",
};
